# Generated by Django 3.1.7 on 2021-07-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labelit", "0012_livecorrectlabel_livecorrecttask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoricaltask",
            name="are_categories_exclusive",
            field=models.BooleanField(
                default=True,
                verbose_name="\n        If true, the annotator cannot select more than one category.\n        ",
            ),
        ),
    ]
