# Generated by Django 3.1.7 on 2021-08-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelit', '0015_auto_20210727_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedtranscriptsegment',
            name='transcript',
            field=models.TextField(blank=True, null=True, verbose_name='The transcript to correct'),
        ),
    ]
