# Generated by Django 3.1.7 on 2022-01-21 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("labelit", "0020_completeddocumentannotatorpair"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completeddocumentannotatorpair",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="labelit.document"
            ),
        ),
    ]
