# Generated by Django 3.1.7 on 2022-03-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labelit", "0029_auto_20220316_0817"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
