# Generated by Django 3.1.7 on 2022-09-08 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("labelit", "0036_project_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioRegionLabel",
            fields=[
                (
                    "label_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="labelit.label",
                    ),
                ),
                ("start", models.FloatField(verbose_name="start time in seconds")),
                ("end", models.IntegerField(verbose_name="end time in seconds")),
            ],
            bases=("labelit.label",),
        ),
        migrations.CreateModel(
            name="AudioRegionTask",
            fields=[
                (
                    "task_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="labelit.task",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="blue",
                        max_length=500,
                        verbose_name="Color for this task",
                    ),
                ),
            ],
            bases=("labelit.task",),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description of the project"
            ),
        ),
    ]
