# Generated by Django 3.1.7 on 2022-09-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labelit", "0037_auto_20220908_1801"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audioregionlabel",
            name="end",
            field=models.FloatField(verbose_name="end time in seconds"),
        ),
    ]
