# Generated by Django 3.1.7 on 2022-10-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labelit", "0039_auto_20220929_0952"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
