# Generated by Django 3.1.7 on 2022-10-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelit', '0041_auto_20221011_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
