apiVersion: v1
kind: Service
metadata:
  name: labelit-backend
  labels:
    app: labelit
    type: backend
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: labelit
    type: backend
