apiVersion: v1
kind: Service
metadata:
  name: labelit-frontend
  labels:
    app: labelit
    type: frontend
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: labelit
    type: frontend
