FROM node:18-alpine as build-stage

WORKDIR /app

COPY . /app/

RUN npm install

RUN npm run build

###################################

FROM nginx:stable-alpine as production-stage

COPY nginx.conf /etc/nginx/nginx.conf

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=build-stage /app/dist .

COPY prod.entrypoint.sh /entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]
