repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.8
        files: |
          (?x)^(
            .*\.py
          )$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        additional_dependencies:
        - prettier@2.8.4
        files: |
          (?x)^(
            .github|
            frontend\/.*
          )$
