ARG PYTHON_VERSION="3.8"
FROM python:${PYTHON_VERSION}-bullseye  AS build-stage

ENV PYTHONUNBUFFERED=1
ENV PACKAGE="audiowaveform"
ENV PACKAGE_VERSION="1.6.0"
ENV PACKAGE_REVISION="1"
ENV PACKAGE_REVISION_DISTRIBUTION="1"
ENV PACKAGE_SOURCE="https://github.com/bbc/audiowaveform.git"

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    libpq-dev \
    g++ \
    cmake \
 && apt-get clean
 
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    libsndfile-dev libmad0-dev libid3tag0-dev libboost-all-dev libgd-dev zlib1g-dev\
 && apt-get clean

RUN git clone $PACKAGE_SOURCE \
 && cd audiowaveform \
 && wget https://github.com/google/googletest/archive/release-1.12.1.tar.gz \
 && tar xzf release-1.12.1.tar.gz \
 && ln -s googletest-release-1.12.1 googletest 

RUN cd audiowaveform \
 && mkdir build \
 && cd build \
 && cmake .. \
 && make 

RUN cd audiowaveform/build \
 && make install

RUN which audiowaveform
RUN audiowaveform --version


#####################################################3


FROM python:${PYTHON_VERSION}-slim-bullseye 

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    libpq-dev \
    g++ \
    ffmpeg \
 && apt-get clean

# libmad, libsndfile, libid3tag, gd and boost are req for audiowaveform
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    libsndfile-dev libmad0-dev libid3tag0-dev libboost-all-dev libgd-dev zlib1g-dev\
 && apt-get clean
 
COPY --from=build-stage /usr/local/bin/audiowaveform /usr/local/bin/

WORKDIR /code
COPY ./backend/requirements-all.txt /code/
RUN pip install -r requirements.txt

COPY ./backend/src /code/

CMD python manage.py runserver 0.0.0.0:8000

# RUN pip install debugpy

# WORKDIR /code/
# CMD ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "manage.py", "runserver", "0.0.0.0:8000"]
