site_name: Labelit documentation

# Documentation and theme
theme:
  name: 'material'
  logo: 'assets/logo_le_voice_lab.png'
  features:
    - toc.integrate

# Options
extra:
  palette:
    primary: '#AC00A9'
    accent: '#AC00A9'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'


extra_css: [ extra.css ]

plugins:
  - i18n:
      languages:
        fr: "Français"
        en: "English"
      default_language: "en"
      no_translation:
        fr: "Cette page n'est pas encore traduite en français."
        en: "This page isn't translated to English"
      translate_nav:
        fr:
          Getting started: "Guide de prise en main"
          How to deploy ?: "Comment deployer ?"

nav:
  - index.md
  # TODO
  # - index.fr.md
  - Getting started:
    - getting_started/01.local_installation.md
    # TODO
    # - getting_started/01.local_installation.fr.md
    - getting_started/02.register_users.md
    - getting_started/03.first_dataset.md
    - getting_started/04.first_task.md
    - getting_started/05.first_project.md
    - getting_started/06.assign_work.md
    - getting_started/07.annotate.md
  - How to deploy ?:
    - how_to_deploy/01.requirements.md
    - how_to_deploy/02.helm_chart.md
    - how_to_deploy/03.environment_variables.md
