[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Labelit"
authors = [{name = "Batvoice Technologies for LeVoiceLab", email = "contact@batvoice.com"},]
dynamic = ["version", "description"]
