ARG PYTHON_VERSION="3.8"
FROM ubuntu:jammy

RUN apt-get update && \
   apt-get install -y software-properties-common && \
   apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4C1BCDE2763923D8 && \
   apt-get update && \
   add-apt-repository ppa:chris-needham/ppa && \
   apt-get update
RUN apt-get install -y -f \
      # for postgres client
      libpq-dev \
      ffmpeg \
      audiowaveform \
      # For pip
      python3-pip python3-dev && \
   apt-get clean

RUN echo "PYTHON"
RUN python3 --version

WORKDIR /code
COPY requirements-dev.txt /code/
RUN pip install -r requirements-dev.txt

COPY src /code/

CMD python src/manage.py runserver 0.0.0.0:8000
