# Generated by Django 3.1.7 on 2021-07-14 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("labelit", "0009_project_timer_inactivity_threshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimedTranscript",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimedTranscriptSegment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transcript",
                    models.TextField(verbose_name="The transcript to correct"),
                ),
                (
                    "timed_transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="labelit.timedtranscript",
                    ),
                ),
            ],
        ),
    ]
