# Generated by Django 3.1.7 on 2021-07-14 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("labelit", "0011_auto_20210714_1249"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveCorrectTask",
            fields=[
                (
                    "task_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="labelit.task",
                    ),
                ),
                (
                    "validator",
                    models.CharField(
                        default="labelit.validators.base_transcription_validator.BaseTranscriptionValidator",
                        max_length=500,
                        verbose_name="Dotted path to the validator class",
                    ),
                ),
            ],
            bases=("labelit.task",),
        ),
        migrations.CreateModel(
            name="LiveCorrectLabel",
            fields=[
                (
                    "label_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="labelit.label",
                    ),
                ),
                (
                    "transcript",
                    models.TextField(
                        blank=True, default="", verbose_name="the transcript"
                    ),
                ),
                (
                    "timed_transcript_segment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="labelit.timedtranscriptsegment",
                    ),
                ),
            ],
            bases=("labelit.label",),
        ),
    ]
