# Generated by Django 3.1.7 on 2022-03-11 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("labelit", "0024_dataset_is_streamed"),
        ("labelit", "0026_auto_20220228_1016"),
    ]

    operations = []
