# Generated by Django 3.1.7 on 2022-03-16 08:13

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labelit", "0027_merge_20220311_0718"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataset",
            name="metadata",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="metadata",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
    ]
