# Generated by Django 3.1.7 on 2022-04-27 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("labelit", "0034_nestedcategoricallabel_nestedcategoricaltask"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="target_deadline",
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name="The target date at which we want the target number of documents to be annotated",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="target_num_documents",
            field=models.IntegerField(
                default=0,
                verbose_name="The target number of documents for this project",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="nestedcategoricallabel",
            name="parent_label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nested_children_labels",
                to="labelit.nestedcategoricallabel",
            ),
        ),
    ]
