# Generated by Django 4.1.7 on 2023-03-11 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("labelit", "0043_project_enable_region_annotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="task_presentation",
            field=models.CharField(
                choices=[("list", "list"), ("sequence", "sequence")],
                default="list",
                max_length=3000,
                verbose_name="Configures how tasks are presented to annotators - as a list containing a task, in sequence, etc.",
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="label",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
