# Generated by Django 4.1.7 on 2023-03-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labelit", "0044_project_task_presentation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
