# Generated by Django 4.1.7 on 2023-03-12 19:28

from django.db import migrations, models
import django.db.models.deletion


### IMPORTANT NOTE !!! THis may cause data loss, TODO: data migration for projects % tasks

class Migration(migrations.Migration):
    dependencies = [
        ("labelit", "0045_task_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labelit.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="labelit.task"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
          model_name='project',
          name='tasks',
        ),
        migrations.AddField(
          model_name='project',
          name='tasks',
          field=models.ManyToManyField(related_name='projects', through='labelit.ProjectTask', to='labelit.Task'),
        ),
    ]


"""
migrations.AlterField(
    model_name="project",
    name="tasks",
    field=models.ManyToManyField(
        related_name="projects",
        through="labelit.ProjectTask",
        to="labelit.task",
    ),
),
"""