# Generated by Django 4.1.7 on 2023-04-07 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("labelit", "0045_remove_dataset_is_streamed"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=1,
                        verbose_name="order in which the task is shown during annotation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labelit.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="labelit.task"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="project",
            name="tasks",
        ),
        migrations.AddField(
            model_name="project",
            name="tasks",
            field=models.ManyToManyField(
                related_name="projects",
                through="labelit.ProjectTask",
                to="labelit.Task",
            ),
        ),
    ]
