# Generated by Django 4.1.7 on 2023-03-18 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("labelit", "0047_remove_task_priority_projecttask_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projecttask",
            old_name="group",
            new_name="project",
        ),
    ]
