name: Backend tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
      - develop

env:
  DB_USER: postgres
  DB_NAME: test
  DB_PASSWORD: postgres
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
  DB_HOST: 127.0.0.1
  AUDIO_FILE_STORAGE: storages.backends.s3boto3.S3Boto3Storage
  IMAGE_FILE_STORAGE: storages.backends.s3boto3.S3Boto3Storage
  AWS_S3_OPTIONS: local
  AWS_ENDPOINT_URL: http://minio:9000/

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      minio:
        image: fclairamb/minio-github-actions
        ports:
          - 9000:9000
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        working-directory: backend/src
        run: |
          pytest
